#!/usr/local/bin/perl

sub ents_to_unicode
{
    my($e) = @_;

    # These were after the unless ... block - God knows why!  SIH 27.6.14
    $e =~ s|&shy;||go;
    $e =~ s|&en;|&ensp;|go;
    $e =~ s|&cq;|&rsquo;|go;
    $e =~ s|&oq;|&lsquo;|go;
    $e =~ s|&asp;|&lsquo;|gio;
    $e =~ s|&ddd;|&hellip;|gio;
    $e =~ s|&th;|&thorn;|gio;

    $e =~ s|(&[^; ]*)hacek;|$1caron;|gio;
    $e =~ s|(&[^; ]*)breve;|$1caron;|gio;
    $e =~ s|(&[^; ]*)bar;|$1macr;|gio;
    $e =~ s|(&[a-z]*)ced;|$1cedil;|gio;
    $e =~ s|(&[^; ]*)dabove;|$1dot;|gio;    
    $e =~ s|(&[^; ]*)hook;|$1ogon;|gio;    

    unless ($NO_SYM_CHANGE)
    {
	$e =~ s|&Dagger;|&\#x2021;|go;
	$e =~ s|&Prime;|&\#x2033;|go;
	$e =~ s|&arrow;|&\#x279E;|go;
	$e =~ s|&blank;|&\#x2423;|go;
	$e =~ s|&blarrow;|&\#x279E;|go;
	$e =~ s|&blk12;|&\#x2592;|go;
	$e =~ s|&blk14;|&\#x2591;|go;
	$e =~ s|&blk34;|&\#x2593;|go;
	$e =~ s|&block;|&\#x2588;|go;
	$e =~ s|&bull;|&\#x2022;|go;
	$e =~ s|&careof;|&\#x2105;|go;
	$e =~ s|&caret;|&\#x2038;|go;
	$e =~ s|&check;|&\#x2713;|go;
	$e =~ s|&cir;|&\#x25CB;|go;
	$e =~ s|&clubs;|&\#x2663;|go;
	$e =~ s|&co2;|CO<z_sub>2</z_sub>|gio;
	$e =~ s|&copy;|&\#x00A9;|go;
	$e =~ s|&copysr;|&\#x2117;|go;
#	s|&coresym;|&\#x2605;|gio;
	$e =~ s|&cross;|&\#x2717;|go;
	$e =~ s|&crossl;|&\#x271D;|go;
	$e =~ s|&crotchet;|&\#x1D15F;|go;
	$e =~ s|&cuberoot;|&\#x221B;|go;
	$e =~ s|&curren;|&\#x00A4;|go;
	$e =~ s|&dagger;|&\#x2020;|go;
	$e =~ s|&darr;|&\#x2193;|go;
	$e =~ s|&dash;|&\#x2010;|go;
	$e =~ s|&deg;|&\#x00B0;|go;
	$e =~ s|&delta;|&\#x03B4;|go;
	$e =~ s|&diams;|&\#x2666;|go;
	$e =~ s|&ditto;|&\#x3003;|go;
	$e =~ s|&dlcrop;|&\#x230D;|go;
	$e =~ s|&dp;|.|go;
	$e =~ s|&drcrop;|&\#x230C;|go;
	$e =~ s|&dtri;|&\#x25BF;|go;
	$e =~ s|&dtrif;|&\#x25BE;|go;
	$e =~ s|&emsp13;|&\#x2004;|go;
	$e =~ s|&emsp14;|&\#x2005;|go;
	$e =~ s|&emsp;|&\#x2003;|go;
	$e =~ s|&ensp;|&\#x2002;|go;
	$e =~ s|&euro;|&\#x20AC;|go;
	$e =~ s|&female;|&\#x2640;|go;
	$e =~ s|&flat;|&\#x266D;|go;
	$e =~ s|&frac12;|&\#x00BD;|go;
	$e =~ s|&frac13;|&\#x2153;|go;
	$e =~ s|&frac14;|&\#x00BC;|go;
	$e =~ s|&frac15;|&\#x2155;|go;
	$e =~ s|&frac16;|&\#x2159;|go;
	$e =~ s|&frac18;|&\#x215B;|go;
	$e =~ s|&frac23;|&\#x2154;|go;
	$e =~ s|&frac25;|&\#x2156;|go;
	$e =~ s|&frac34;|&\#x00BE;|go;
	$e =~ s|&frac35;|&\#x2157;|go;
	$e =~ s|&frac38;|&\#x215C;|go;
	$e =~ s|&frac45;|&\#x2158;|go;
	$e =~ s|&frac56;|&\#x215A;|go;
	$e =~ s|&frac58;|&\#x215D;|go;
	$e =~ s|&frac78;|&\#x215E;|go;
	$e =~ s|&frown;|&\#x2322;|go;
	$e =~ s|&gql;|&\#x201E;|go;
	$e =~ s|&gqr;|&\#x201C;|go;
	$e =~ s|&h2o;|H<z_sub>2</z_sub>O|gio;
	$e =~ s|&hairsp;|&\#x200A;|go;
	$e =~ s|&hearts;|&\#x2665;|go;
	$e =~ s|&hellip;|&\#x2026;|go;
	$e =~ s|&horbar;|&\#x2015;|go;
	$e =~ s|&hybull;|&\#x2043;|go;
	$e =~ s|&hyphen;|&\#x2010;|go;
	$e =~ s|&incare;|&\#x2105;|go;
	$e =~ s|&infin;|&\#x221E;|go;
	$e =~ s|&larr;|&\#x2190;|go;
	$e =~ s|&ldquo;|&\#x201C;|go;
	$e =~ s|&ldquor;|&\#x201E;|go;
	$e =~ s|&lhblk;|&\#x2584;|go;
	$e =~ s|&loz;|&\#x25CA;|go;
	$e =~ s|&lozf;|&\#x2726;|go;
	$e =~ s|&lsquo;|&\#x2018;|go;
	$e =~ s|&lsquor;|&\#x201A;|go;
	$e =~ s|&ltri;|&\#x25C3;|go;
	$e =~ s|&ltrif;|&\#x25C2;|go;
	$e =~ s|&male;|&\#x2642;|go;
	$e =~ s|&malt;|&\#x2720;|go;
	$e =~ s|&marker;|&\#x25AE;|go;
	$e =~ s|&mdash;|&\#x2014;|go;
	$e =~ s|&minus;|&\#x2212;|go;
	$e =~ s|&mldr;|&\#x2026;|go;
	$e =~ s|&mu;|&\#x03BC;|go;
	$e =~ s|&natur;|&\#x266E;|go;
	$e =~ s|&nbthinsp.*?;|&\#x2009;|go;
	$e =~ s|&ndash;|&\#x2013;|go;
	$e =~ s|&ne;|&\#x2260;|go; 
	$e =~ s|&nldr;|&\#x2025;|go;
	$e =~ s|&not;|&\#x00AC;|go;
	$e =~ s|&num;|&\#x0023;|go;
	$e =~ s|&numsp;|&\#x2007;|go;
	$e =~ s|&odblac;|&\#x0151;|go;
	$e =~ s|&ohm;|&\#x2126;|go;
	$e =~ s|&omega;|&\#x03C9;|go;
	$e =~ s|&omicron;|o|go;
	$e =~ s|&ordf;|&\#x00AA;|go;
	$e =~ s|&ordm;|&\#x00BA;|go;
	$e =~ s|&para;|&\#x00B6;|go;
	$e =~ s|&pause;||go;
	$e =~ s|&phis;|&phi;|go;
	$e =~ s|&phi;|&\#x0278;|go;
	$e =~ s|&phone;|&\#x260E;|go;
	$e =~ s|&pi;|&\#x03C0;|go;
	$e =~ s|&pir2;|&\#x03C0;r&\#x00B2;|go; 
	$e =~ s|&plus;|&\#x002B;|go;
	$e =~ s|&plusmn;|&\#x00B1;|go;
	$e =~ s|&prime;|&\#x2032;|go;
	$e =~ s|&psi;|&\#x03C8;|go;
	$e =~ s|&puncsp;|&\#x2008;|go;
	$e =~ s|&pvarr;|&\#x2194;|go;
	$e =~ s|&quaver;|&\#x266A;|go;
	$e =~ s|&radic;|&\#x221A;|go;
	$e =~ s|&rarr;|&\#x2192;|go;
	$e =~ s|&rdquo;|&\#x201D;|go;
	$e =~ s|&rdquor;|&\#x201C;|go;
	$e =~ s|&rect;|&\#x25AD;|go;
	$e =~ s|&reg;|&\#x00AE;|go;
	$e =~ s|&rho;|&\#x03C1;|go;
	$e =~ s|&rsquo;|&\#x2019;|go;
	$e =~ s|&rsquor;|&\#x2018;|go;
	$e =~ s|&rtri;|&\#x25B9;|go;
	$e =~ s|&rtrif;|&\#x25B8;|go;
	$e =~ s|&rx;|&\#x211E;|go;
	$e =~ s|&semibrev;|&\#x1D15D;|go;
	$e =~ s|&semiquav;|&\#x1D161;|go;
	$e =~ s|&sext;|&\#x2736;|go;
	$e =~ s|&sharp;|&\#x266F;|go;
	$e =~ s|&sigma;|&\#x03C3;|go;
	$e =~ s|&smile;|&\#x2323;|go;
	$e =~ s|&spades;|&\#x2660;|go;
	$e =~ s|&spc_sl2;| |go;
	$e =~ s|&spc_ssym;| |go;
	$e =~ s|&spc_xhm;| |go;
	$e =~ s|&squ;|&\#x25A1;|go;
	$e =~ s|&squf;|&\#x25AA;|go;
	$e =~ s|&star;|&\#x22C6;|go;
	$e =~ s|&starf;|&\#x2605;|go;
	$e =~ s|&sung;|&\#x2669;|go;
	$e =~ s|&synsep;|&#x2027;|go;
	$e =~ s|&target;|&\#x2316;|go;
	$e =~ s|&tau;|&\#x03C4;|go;
	$e =~ s|&tclef;|&\#x1D120;|go;
	$e =~ s|&telrec;|&\#x2315;|go;
	$e =~ s|&thinsp;|&\#x2009;|go;
	$e =~ s|&thinsp[^;]*;|&\#x2009;|go;
	$e =~ s|&tick;|&\#x2713;|go;
	$e =~ s|&trade;|&\#x2122;|go;
	$e =~ s|&uarr;|&\#x2191;|go;
	$e =~ s|&uhblk;|&\#x2580;|go;
	$e =~ s|&ulcrop;|&\#x230F;|go;
	$e =~ s|&urcrop;|&\#x230E;|go;
	$e =~ s|&utri;|&\#x25B5;|go;
	$e =~ s|&utrif;|&\#x25B4;|go;
	$e =~ s|&vellip;|&\#x22EE;|go;
#	s|&w;|&#x2022;|go;
	$e =~ s|&w;|&#x00B7;|go;
	$e =~ s|&xi;|&\#x03BE;|go;
	$e =~ s|&xrefarrow;|&#x27B1;|go;
	$e =~ s|&xrsym;|&#x27B1;|gio;

    }

    $e =~ s|&ldbelow;|&\#x013C;|go;
    $e =~ s|&ndbelow;|&\#x0146;|go;
    $e =~ s|&rdbelow;|&\#x0157;|go;
    $e =~ s|&sdbelow;|&\#x015F;|go;
    $e =~ s|&tdbelow;|&\#x0163;|go;
    $e =~ s|&kdbelow;|&\#x0137;|go;

    
    $e =~ s|&AElig;|&\#x00C6;|go;
    $e =~ s|&Aacute;|&\#x00C1;|go;
    $e =~ s|&Aang;|&\#x00C5;|go;
    $e =~ s|&Abreve;|&\#x0102;|go;
    $e =~ s|&Acirc;|&\#x00C2;|go;
    $e =~ s|&Agrave;|&\#x00C0;|go;
    $e =~ s|&Ahacek;|&\#x0102;|go;
    $e =~ s|&Amac;|&\#x0100;|go;
    $e =~ s|&Amacr?;|&\#x0100;|go;
    $e =~ s|&Aogon;|&\#x0104;|go;
    $e =~ s|&Aring;|&\#x00C5;|go;
    $e =~ s|&Atilde;|&\#x00C3;|go;
    $e =~ s|&Auml;|&\#x00C4;|go;
    $e =~ s|&Cacute;|&\#x0106;|go;
    $e =~ s|&Cbreve;|&\#x010C;|go;
    $e =~ s|&Ccaron;|&\#x010C;|go;
    $e =~ s|&Ccedil;|&\#x00C7;|go;
    $e =~ s|&Ccirc;|&\#x0108;|go;
    $e =~ s|&Cdot;|&\#x010A;|go;
    $e =~ s|&Chacek;|&\#x010C;|go;
    $e =~ s|&Dbreve;|&\#x010E;|go;
    $e =~ s|&Dcaron;|&\#x010E;|go;
    $e =~ s|&Delta;|&\#x0394;|go;
    $e =~ s|&Dot;|&\#x00B7;|go;
    $e =~ s|&Dstrok;|&\#x0110;|go;
    $e =~ s|&ENG;|&\#x014A;|go;
    $e =~ s|&ETH;|&\#x00D0;|go;
    $e =~ s|&Eacute;|&\#x00C9;|go;
    $e =~ s|&Ebreve;|&\#x011A;|go;
    $e =~ s|&Ecaron;|&\#x011A;|go;
    $e =~ s|&Ecirc;|&\#x00CA;|go;
    $e =~ s|&Edot;|&\#x0116;|go;
    $e =~ s|&Egrave;|&\#x00C8;|go;
    $e =~ s|&Emac;|&\#x0112;|go;
    $e =~ s|&Emacr?;|&\#x0112;|go;
    $e =~ s|&Eogon;|&\#x0118;|go;
    $e =~ s|&Euml;|&\#x00CB;|go;
    $e =~ s|&Gamma;|&\#x0393;|go;
    $e =~ s|&Gbreve;|&\#x011E;|go;
    $e =~ s|&Gcedil;|&\#x0122;|go;
    $e =~ s|&Gcirc;|&\#x011C;|go;
    $e =~ s|&Gdot;|&\#x0120;|go;
    $e =~ s|&Hcirc;|&\#x0124;|go;
    $e =~ s|&Hstrok;|&\#x0126;|go;
    $e =~ s|&IJlig;|&\#x0132;|go;
    $e =~ s|&Iacute;|&\#x00CD;|go;
    $e =~ s|&Icirc;|&\#x00CE;|go;
    $e =~ s|&Idot;|&\#x0130;|go;
    $e =~ s|&Igrave;|&\#x00CC;|go;
    $e =~ s|&Imacr?;|&\#x012A;|go;
    $e =~ s|&Iogon;|&\#x012E;|go;
    $e =~ s|&Itilde;|&\#x0128;|go;
    $e =~ s|&Iuml;|&\#x00CF;|go;
    $e =~ s|&Jcirc;|&\#x0134;|go;
    $e =~ s|&Kcedil;|&\#x0136;|go;
    $e =~ s|&Lacute;|&\#x0139;|go;
    $e =~ s|&Lambda;|&\#x039B;|go;
    $e =~ s|&Lbreve;|&\#x013D;|go;
    $e =~ s|&Lcaron;|&\#x013D;|go;
    $e =~ s|&Lcedil;|&\#x013B;|go;
    $e =~ s|&Lcross;|&\#x0141;|go;
    $e =~ s|&Llmiddot;|&\#x013F;|go;
    $e =~ s|&Lmidot;|&\#x013F;|go;
    $e =~ s|&Lstrok;|&\#x0141;|go;
    $e =~ s|&NDASH;|&ndash;|go;
    $e =~ s|&Nacute;|&\#x0143;|go;
    $e =~ s|&Nbreve;|&\#x0147;|go;
    $e =~ s|&Ncaron;|&\#x0147;|go;
    $e =~ s|&Ncedil;|&\#x0145;|go;
    $e =~ s|&Ntilde;|&\#x00D1;|go;
    $e =~ s|&OElig;|&\#x0152;|go;
    $e =~ s|&Oacute;|&\#x00D3;|go;
    $e =~ s|&Ocirc;|&\#x00D4;|go;
    $e =~ s|&Odblac;|&\#x0150;|go;
    $e =~ s|&Ograve;|&\#x00D2;|go;
    $e =~ s|&Omacr?;|&\#x014C;|go;
    $e =~ s|&Omega;|&\#x03A9;|go;
    $e =~ s|&Oslash;|&\#x00D8;|go;
    $e =~ s|&Otilde;|&\#x00D5;|go;
    $e =~ s|&Ouml;|&\#x00D6;|go;
    $e =~ s|&Phi;|&\#x03A6;|go;
    $e =~ s|&Pi;|&\#x03A0;|go;
    $e =~ s|&Psi;|&\#x03A8;|go;
    $e =~ s|&Racute;|&\#x0154;|go;
    $e =~ s|&Rbreve;|&\#x0158;|go;
    $e =~ s|&Rcaron;|&\#x0158;|go;
    $e =~ s|&Rcedil;|&\#x0156;|go;
    $e =~ s|&Sacute;|&\#x015A;|go;
    $e =~ s|&Sbreve;|&\#x0160;|go;
    $e =~ s|&Scaron;|&\#x0160;|go;
    $e =~ s|&Scedil;|&\#x015E;|go;
    $e =~ s|&Scirc;|&\#x015C;|go;
    $e =~ s|&Sigma;|&\#x03A3;|go;
    $e =~ s|&THORN;|&\#x00DE;|go;
    $e =~ s|&Tbreve;|&\#x0164;|go;
    $e =~ s|&Tcaron;|&\#x0164;|go;
    $e =~ s|&Tcedil;|&\#x0162;|go;
    $e =~ s|&Theta;|&\#x0398;|go;
    $e =~ s|&Tstrok;|&\#x0166;|go;
    $e =~ s|&Uacute;|&\#x00DA;|go;
    $e =~ s|&Ubreve;|&\#x016C;|go;
    $e =~ s|&Ucirc;|&\#x00DB;|go;
    $e =~ s|&Udblac;|&\#x0170;|go;
    $e =~ s|&Ugrave;|&\#x00D9;|go;
    $e =~ s|&Umacr?;|&\#x016A;|go;
    $e =~ s|&Uogon;|&\#x0172;|go;
    $e =~ s|&Upsi;|&\#x03D2;|go;
    $e =~ s|&Uring;|&\#x016E;|go;
    $e =~ s|&Utilde;|&\#x0168;|go;
    $e =~ s|&Uuml;|&\#x00DC;|go;
    $e =~ s|&Wcirc;|&\#x0174;|go;
    $e =~ s|&Xi;|&\#x039E;|go;
    $e =~ s|&Yacute;|&\#x00DD;|go;
    $e =~ s|&Ycirc;|&\#x0176;|go;
    $e =~ s|&Yuml;|&\#x0178;|go;
    $e =~ s|&Zacute;|&\#x0179;|go;
    $e =~ s|&Zbreve;|&\#x017D;|go;
    $e =~ s|&Zcaron;|&\#x017D;|go;
    $e =~ s|&Zdot;|&\#x017B;|go;
    $e =~ s|&aacute;|&\#x00E1;|go;
    $e =~ s|&aang;|&\#x00E5;|go;
    $e =~ s|&abcedil;|&\#x0105;|go;
    $e =~ s|&acaron;|&\#x0103;|go;
    $e =~ s|&acirc;|&\#x00E2;|go;
    $e =~ s|&aeacute;|&\#x01FD;|go;
    $e =~ s|&aelig;|&\#x00E6;|go;
    $e =~ s|&aemac;|&\#x01E3;|go;
    $e =~ s|&agrave;|&\#x00E0;|go;
    $e =~ s|&ahacek;|&\#x0103;|go;
    $e =~ s|&alpha;|&\#x03B1;|go;
    $e =~ s|&amacr?;|&\#x0101;|go;
    $e =~ s|&amp;|&\#x0026;|go;
    $e =~ s|&aogon;|&\#x0105;|go;
    $e =~ s|&ap;|&apos;|go;
    $e =~ s|&apos;|&\#x0027;|go;
    $e =~ s|&aring;|&\#x00E5;|go;
    $e =~ s|&ast;|&\#x002A;|go;
    $e =~ s|&atilde;|&\#x00E3;|go;
    $e =~ s|&auml;|&\#x00E4;|go;
    $e =~ s|&bclef;|&\#x1D122;|go;
    $e =~ s|&beta;|&\#x03B2;|go;
    $e =~ s|&brvbar;|&\#x00A6;|go;
    $e =~ s|&bsol;|&\#x005C;|go;
    $e =~ s|&cacute;|&\#x0107;|go;
    $e =~ s|&cbreve;|&\#x010D;|go;
    $e =~ s|&ccaron;|&\#x010D;|go;
    $e =~ s|&ccedil;|&\#x00E7;|go;
    $e =~ s|&ccirc;|&\#x0109;|go;
    $e =~ s|&cdot;|&\#x010B;|go;
    $e =~ s|&cedil;|&\#x00B8;|go;
    $e =~ s|&cent;|&\#x00A2;|go;
    $e =~ s|&chacek;|&\#x010D;|go;
    $e =~ s|&chi;|&\#x03C7;|go;
    $e =~ s|&circ;|&\#x005E;|go;
    $e =~ s|&colon;|&\#x003A;|go;
    $e =~ s|&comma;|&\#x002C;|go;
    $e =~ s|&commat;|&\#x0040;|go;
    $e =~ s|&dbreve;|&\#x010F;|go;
    $e =~ s|&dcaron;|&\#x010F;|go;
    $e =~ s|&divide;|&\#x00F7;|go;
    $e =~ s|&dlessi;|&\#x0131;|go;
    $e =~ s|&dollar;|&\#x0024;|go;
    $e =~ s|&dstrok;|&\#x0111;|go;
    $e =~ s|&eacute;|&\#x00E9;|go;
    $e =~ s|&ebcedil;|&\#x0119;|go;
    $e =~ s|&ebreve;|&\#x011B;|go;
    $e =~ s|&ecaron;|&\#x011B;|go;
    $e =~ s|&ecirc;|&\#x00EA;|go;
    $e =~ s|&edot;|&\#x0117;|go;
    $e =~ s|&egrave;|&\#x00E8;|go;
    $e =~ s|&emacr?;|&\#x0113;|go;
    $e =~ s|&eng;|&\#x014B;|go;
    $e =~ s|&eogon;|&\#x0119;|go;
    $e =~ s|&epsi;|&\#x03F5;|go;
    $e =~ s|&equals;|&\#x003D;|go;
    $e =~ s|&eta;|&\#x03B7;|go;
    $e =~ s|&eth;|&\#x00F0;|go;
    $e =~ s|&euml;|&\#x00EB;|go;
    $e =~ s|&excl;|&\#x0021;|go;
    $e =~ s|&f1d1000;|1/1000|go;
    $e =~ s|&f1d100;|1/100|go;
    $e =~ s|&f1d10;|1/10|go;
    $e =~ s|&f1d15;|1/15|go;
    $e =~ s|&f1d16;|1/16|go;
    $e =~ s|&ffilig;|&\#xFB03;|go;
    $e =~ s|&fflig;|&\#xFB00;|go;
    $e =~ s|&ffllig;|&\#xFB04;|go;
    $e =~ s|&filig;|&\#xFB01;|go;
    $e =~ s|&fllig;|&\#xFB02;|go;
    $e =~ s|&frac17;|1/7|go;
    $e =~ s|&frac19;|1/9|go;
    $e =~ s|&frac76;|7/6|go;
    $e =~ s|&gacute;|&\#x01F5;|go;
    $e =~ s|&gamma;|&\#x03B3;|go;
    $e =~ s|&gcaron;|&\#x011F;|go;
    $e =~ s|&gcirc;|&\#x011D;|go;
    $e =~ s|&gdot;|&\#x0121;|go;
    $e =~ s|&gdp;|,|go;
    $e =~ s|&grave;|&\#x0060;|go;
    $e =~ s|&grslash;|/|go;
    $e =~ s|&gt;|&\#x003E;|go;
    $e =~ s|&half;|&\#x00BD;|go;
    $e =~ s|&half;|&frac12;|go;
    $e =~ s|&hcirc;|&\#x0125;|go;
    $e =~ s|&hstrok;|&\#x0127;|go;
    $e =~ s|&iacute;|&\#x00ED;|go;
    $e =~ s|&icaron;|&\#x012D;|go;
    $e =~ s|&icirc;|&\#x00EE;|go;
    $e =~ s|&iexcl;|&\#x00A1;|go;
    $e =~ s|&igrave;|&\#x00EC;|go;
    $e =~ s|&ijlig;|&\#x0133;|go;
    $e =~ s|&imacr?;|&\#x012B;|go;
    $e =~ s|&inodot;|&\#x0131;|go;
    $e =~ s|&iogon;|&\#x012F;|go;
    $e =~ s|&iota;|&\#x03B9;|go;
    $e =~ s|&iquest;|&\#x00BF;|go;
    $e =~ s|&itilde;|&\#x0129;|go;
    $e =~ s|&iuml;|&\#x00EF;|go;
    $e =~ s|&jcirc;|&\#x0135;|go;
    $e =~ s|&kappa;|&\#x03BA;|go;
    $e =~ s|&kcedil;|&\#x0137;|go;
    $e =~ s|&key;|&star;|go;
    $e =~ s|&key_space;| |go;
    $e =~ s|&kgreen;|&\#x0138;|go;
    $e =~ s|&lacute;|&\#x013A;|go;
    $e =~ s|&lambda;|&\#x03BB;|go;
    $e =~ s|&laquo;|&\#x00AB;|go;
    $e =~ s|&lbreve;|&\#x013E;|go;
    $e =~ s|&lcaron;|&\#x013E;|go;
    $e =~ s|&lcedil;|&\#x013C;|go;
    $e =~ s|&lcross;|&\#x0142;|go;
    $e =~ s|&lcub;|&\#x007B;|go;
    $e =~ s|&line;|&#x005F;|go;
    $e =~ s|&lmidot;|&\#x0140;|go;
    $e =~ s|&lowbar;|&\#x005F;|go;
    $e =~ s|&lpar;|&\#x0028;|go;
    $e =~ s|&lsqb;|&\#x005B;|go;
    $e =~ s|&lstrok;|&\#x0142;|go;
    $e =~ s|&lt;|&\#x003C;|go;
    $e =~ s|&macr?;|&\#x00AF;|go;
    $e =~ s|&micro;|&\#x00B5;|go;
    $e =~ s|&middot;|&\#x00B7;|go;
    $e =~ s|&minim;|&\#x1D15E;|go;
    $e =~ s|&nacute;|&\#x0144;|go;
    $e =~ s|&napos;|&\#x0149;|go;
    $e =~ s|&nbhyph;|-|go;
    $e =~ s|&nbhyphen;|-|go;
    $e =~ s|&nbreve;|&\#x0148;|go;
    $e =~ s|&nbsp;|&\#x00A0;|go;
    $e =~ s|&nbthinsp;|&thinsp;|go;
    $e =~ s|&ncaron;|&\#x0148;|go;
    $e =~ s|&ncedil;|&\#x0146;|go;
    $e =~ s|&ntilde;|&\#x00F1;|go;
    $e =~ s|&nu;|&\#x03BD;|go;
    $e =~ s|&oacute;|&\#x00F3;|go;
    $e =~ s|&ob;|/|goi;
    $e =~ s|&ocirc;|&\#x00F4;|go;
    $e =~ s|&oe;|&\#x0153;|go;
    $e =~ s|&oelig;|&\#x0153;|go;
    $e =~ s|&ograve;|&\#x00F2;|go;
    $e =~ s|&omacr?;|&\#x014D;|go;
    $e =~ s|&oogon;|&\#x01EB;|go; # close but ...
    $e =~ s|&oslash;|&\#x00F8;|go;
    $e =~ s|&otilde;|&\#x00F5;|go;
    $e =~ s|&ouml;|&\#x00F6;|go;
    $e =~ s|&p;|&\#x02C8;|go; 
    $e =~ s|&percnt;|&\#x0025;|go;
    $e =~ s|&period;|&\#x002E;|go;
    $e =~ s|&pipe;|&#x007C;|go;
    $e =~ s|&pound;|&\#x00A3;|go;
    $e =~ s|&pound_currency;|&\#x00A3;|go;
    $e =~ s|&poundce;|&\#x00A3;|go;
    $e =~ s|&pstress;|&\#x02C8;|go; 
    $e =~ s|&quest;|&\#x003F;|go;
    $e =~ s|&quot;|&\#x0022;|go;
    $e =~ s|&racute;|&\#x0155;|go;
    $e =~ s|&raquo;|&\#x00BB;|go;
    $e =~ s|&rbreve;|&\#x0159;|go;
    $e =~ s|&rcaron;|&\#x0159;|go;
    $e =~ s|&rcedil;|&\#x0157;|go;
    $e =~ s|&rcub;|&\#x007D;|go;
    $e =~ s|&rpar;|&\#x0029;|go;
    $e =~ s|&rsqb;|&\#x005D;|go;
    $e =~ s|&s;|&#x02CC;|go;
    $e =~ s|&sacute;|&\#x015B;|go;
    $e =~ s|&sbreve;|&\#x0161;|go;
    $e =~ s|&scaron;|&\#x0161;|go;
    $e =~ s|&sced;|&\#x015F;|go;
    $e =~ s|&scedil;|&\#x015F;|go;
    $e =~ s|&scirc;|&\#x015D;|go;
    $e =~ s|&sect;|&\#x00A7;|go;
    $e =~ s|&semi;|&\#x003B;|go;
    $e =~ s|&shy;|&\#x00AD;|go;
    $e =~ s|&sol;|/|go;
    $e =~ s|&sol;|/|goi;
    $e =~ s|&sstress;|&#x02CC;|go;
    $e =~ s|&sub([0-9]+);|<z_sub>\1</z_sub>|go;
    $e =~ s|&sup([0-9]+);|<z_sup>\1</z_sup>|go;
    $e =~ s|&sup1;|&\#x00B9;|go;
    $e =~ s|&sup2;|&\#x00B2;|go;
    $e =~ s|&sup3;|&\#x00B3;|go;
    $e =~ s|&supminus([0-9]+);|<z_sup>-\1</z_sup>|go;
    $e =~ s|&szlig;|&\#x00DF;|go;
    $e =~ s|&tbreve;|&\#x0165;|go;
    $e =~ s|&tcaron;|&\#x0165;|go;
    $e =~ s|&tcedil;|&\#x0163;|go;
    $e =~ s|&thetas;|&theta;|go;
    $e =~ s|&theta;|&\#x03B8;|go;
    $e =~ s|&thorn;|&\#x00FE;|go;
    $e =~ s|&tilde;|&\#x02DC;|go;
    $e =~ s|&tilde;|~|go;
    $e =~ s|&times;|&\#x00D7;|go;
    $e =~ s|&tstrok;|&\#x0167;|go;
    $e =~ s|&uacute;|&\#x00FA;|go;
    $e =~ s|&uang;|&\#x016F;|go;
    $e =~ s|&ubreve;|&\#x016D;|go;
    $e =~ s|&ucaron;|&\#x016D;|go;
    $e =~ s|&ucirc;|&\#x00FB;|go;
    $e =~ s|&udblac;|&\#x0171;|go;
    $e =~ s|&ugrave;|&\#x00F9;|go;
    $e =~ s|&umacr?;|&\#x016B;|go;
    $e =~ s|&uogon;|&\#x0173;|go;
    $e =~ s|&upsi;|&\#x03C5;|go;
    $e =~ s|&uring;|&\#x016F;|go;
    $e =~ s|&utilde;|&\#x0169;|go;
    $e =~ s|&uuml;|&\#x00FC;|go;
    $e =~ s|&uumlaut;|&\#x00FC;|go;
    $e =~ s|&verbar;|&\#x007C;|go;
    $e =~ s|&vthinsp;|&thinsp;|go;
    $e =~ s|&wcirc;|&\#x0175;|go;
    $e =~ s|&yacute;|&\#x00FD;|go;
    $e =~ s|&ycirc;|&\#x0177;|go;
    $e =~ s|&yen;|&\#x00A5;|go;
    $e =~ s|&ymacr?;|&\#x04EF;|go;
    $e =~ s|&yuml;|&\#x00FF;|go;
    $e =~ s|&zacute;|&\#x017A;|go;
    $e =~ s|&zbreve;|&\#x017E;|go;
    $e =~ s|&zcaron;|&\#x017E;|go;
    $e =~ s|&zdot;|&\#x017C;|go;
    $e =~ s|&zeta;|&\#x03B6;|go;
    $e =~ s|l&llmiddot;|&\#x0140;|go;


    $e =~ s|&([^; ]*)bbelow;|$1&\#x0331;|gio;    
    $e =~ s|&([^; ]*)dbelow;|$1&\#x0345;|gio;    
    $e =~ s|&([^; ]*)tilde;|$1&\#x0342;|gio; 
    $e =~ s|&([^; ]*)macr?;|$1&\#x0304;|gio;       
    $e =~ s|&([^; ]*)dot;|$1&\#x0307;|gio;    

#   Greek characters ...

    $e =~ s|&Agr;|&\#x0391;|go;	# Alpha
    $e =~ s|&Bgr;|&\#x0392;|go;	# Beta
    $e =~ s|&Dgr;|&\#x0394;|go;	# Delta
    $e =~ s|&EEgr;|&\#x0397;|go;	# Eta
    $e =~ s|&Egr;|&\#x0395;|go;	# Epsilon
    $e =~ s|&Ggr;|&\#x0393;|go;	# Gamma
    $e =~ s|&Igr;|&\#x0399;|go;	# Iota
    $e =~ s|&KHgr;|&\#x03A7;|go;	# Chi
    $e =~ s|&Kgr;|&\#x039A;|go;	# Kappa
    $e =~ s|&Lgr;|&\#x039B;|go;	# Lambda
    $e =~ s|&Mgr;|&\#x039C;|go;	# Mu
    $e =~ s|&Ngr;|&\#x039D;|go;	# Nu
    $e =~ s|&OHgr;|&\#x03A9;|go;	# Omega
    $e =~ s|&Ogr;|&\#x039F;|go;	# Omicron
    $e =~ s|&PHgr;|&\#x03A6;|go;	# Phi
    $e =~ s|&PSgr;|&\#x0308;|go;	# Psi
    $e =~ s|&Pgr;|&\#x03A0;|go;	# Pi
    $e =~ s|&Rgr;|&\#x03A1;|go;	# Rho
    $e =~ s|&Sgr;|&\#x03A3;|go;	# Sigma
    $e =~ s|&THgr;|&\#x0398;|go;	# Theta
    $e =~ s|&Tgr;|&\#x03A4;|go;	# Tau
    $e =~ s|&Ugr;|&\#x03A5;|go;	# Upsilon
    $e =~ s|&Xgr;|&\#x039E;|go;	# Xi
    $e =~ s|&Zgr;|&\#x0396;|go;	# Zeta

    $e =~ s|&agr;|&\#x03B1;|go;	# alpha
    $e =~ s|&bgr;|&\#x03B2;|go;	# beta
    $e =~ s|&dgr;|&\#x03B4;|go;	# delta
    $e =~ s|&eegr;|&\#x03B7;|go;	# eta
    $e =~ s|&egr;|&\#x03B5;|go;	# epsilon
    $e =~ s|&ggr;|&\#x03B3;|go;	# gamma
    $e =~ s|&igr;|&\#x03B9;|go;	# iota
    $e =~ s|&kgr;|&\#x03BA;|go;	# kappa
    $e =~ s|&khgr;|&\#x03C7;|go;	# chi
    $e =~ s|&lgr;|&\#x03BB;|go;	# lambda
    $e =~ s|&mgr;|&\#x03BC;|go;	# mu
    $e =~ s|&ngr;|&\#x03BD;|go;	# nu
    $e =~ s|&ogr;|&\#x03BF;|go;	# omicron
    $e =~ s|&ohgr;|&\#x03C9;|go;	# omega
    $e =~ s|&pgr;|&\#x03C0;|go;	# pi
    $e =~ s|&phgr;|&\#x03C6;|go;	# phi
    $e =~ s|&psgr;|&\#x03C8;|go;	# psi
    $e =~ s|&rgr;|&\#x03C1;|go;	# rho
    $e =~ s|&sgr;|&\#x03C3;|go;	# sigma
    $e =~ s|&tgr;|&\#x03C4;|go;	# tau
    $e =~ s|&thgr;|&\#x03B8;|go;	# theta
    $e =~ s|&ugr;|&\#x03C5;|go;	# upsilon
    $e =~ s|&xgr;|&\#x03BE;|go;	# xi
    $e =~ s|&zgr;|&\#x03B6;|go;	# zeta
    
    return($e);
}

1;
