#!/usr/local/bin/perl

# legacy program ONLY used for some existing licensing conversions - this is superceded by generic_private_use.pl ...

# convert proprietary entities to private use hex character refs ...

sub ents_to_private_use_char_ref

{

    s|&helpisym;|&#xE000;|g;		# white san serif "i" on a coloured or black circular background ...
    s|&coresym;|&#xE001;|g;		# "core entry" right facing key symbol - as used in ald8 book ...
    s|&idsym;|&#xE002;|g;		# white san serif "IDM" on a coloured or black background - background pointed on right side - as used in ald8 book ...
    s|&pvsym;|&#xE003;|g;		# white san serif "PHR V" on a coloured or black background - background pointed on right side - as used in ald8 book ...
    s|&synsym;|&#xE004;|g;		# white san serif "SYN" on a coloured or black background - background a rectangle with rounded ends - as used in ald8 book ...
    s|&coresym_diag;|&#xE005;|g;	# "core entry" diagonal facing key symbol - as used in oad book ...
    s|&unsym;|&#xE006;|g;		# white right facing arrow on a coloured or black circular background ...
}

1;
