#!/usr/local/bin/perl

# perl subroutine to convert proprietary SGML/XML entity references to Unicode private use codepoints ...
# please keep the codepoints in this program as Numerical Character References rather than UTF-8 for legibility ...

sub generic_private_use
{
    s|&nbhyph;|&\#x2011;|gi;
    s|&nbthinsp;|&\#x202F;|gi;
    s|&shy;|&\#x00AD;|gi;
#   FIXED private use characters - the same character form is used across all projects/products ...
#   fixed private use characters are assumed to be in the same style as any surrounding text and are therefore not explicitly tagged ...
    s|&nbmdash;|&#xE10A;|g; # non-breaking em dash ...
#   VARIABLE private use characters - the design is variable depending on the project/product ...
#   look at the appropriate font to see the design of the character for a specific project/product ...
#   variable private use characters are explicitly tagged to aid design ...
#   symbols indicating entry structure ... 
    s|&(cfesym);|<z_$1>&#xE008;</z_$1>|g;	# cfe symbol used before cfe groups ...
    s|&(drsym);|<z_$1>&#xE001;</z_$1>|g;	# derivative symbol used before a single derivative group ...
    s|&(drsyms);|<z_$1>&#xE002;</z_$1>|g;	# derivative symbol used before a multiple derivative groups ...
    s|&(idsym);|<z_$1>&#xE003;</z_$1>|g;	# idiom symbol used before a single idiom group ...
    s|&(idsyms);|<z_$1>&#xE004;</z_$1>|g;	# idiom symbol used before a multiple idiom groups ...
    s|&(lisym_cit);|<z_$1>&#xE0D5;</z_$1>|g;	# citation list item symbol ...
    s|&(lisym_def);|<z_$1>&#xE0D3;</z_$1>|g;	# definition list item symbol ...
    s|&(lisym_exa);|<z_$1>&#xE0D4;</z_$1>|g;	# example list item symbol ...
    s|&(psym);|<z_$1>&#xE007;</z_$1>|g;		# part of speech section symbol ...
    s|&(pvsym);|<z_$1>&#xE005;</z_$1>|g;	# phrasal verb symbol used before a single phrasal verb group ...
    s|&(pvsyms);|<z_$1>&#xE006;</z_$1>|g;	# phrasal verb symbol used before a multiple phrasal verb groups ...
    s|&(sdsym);|<z_$1>&#xE000;</z_$1>|g;	# "signpost" sense division symbol ...
    s|&(tssym);|<z_$1>&#xE0CC;</z_$1>|g;	# start of translations symbol...    
#   symbols indicating entry or sub-entry status ... 
    s|&(awlsym);|<z_$1>&#xE03B;</z_$1>|g;	# academic word list symbol ...
    s|&(coresym);|<z_$1>&#xE03A;</z_$1>|g;	# core entry symbol ...
#	usage note symbols - ie symbols which begin the text of a note ...
#   tabbed usage note headings should be repesented by tagged text rather than a private use character ...	
    s|&(uncollsym);|<z_$1>&#xE047;</z_$1>|g;	# usage note collocations symbol ...
    s|&(uncompsym);|<z_$1>&#xE048;</z_$1>|g;	# usage note comp symbol ...
    s|&(uncultsym);|<z_$1>&#xE040;</z_$1>|g;	# usage note culture symbol ...
    s|&(undrivsym);|<z_$1>&#xE045;</z_$1>|g;	# usage note derivative symbol ...
    s|&(ungramsym);|<z_$1>&#xE041;</z_$1>|g;	# usage note grammar symbol ...
    s|&(unhelpsym);|<z_$1>&#xE042;</z_$1>|g;	# usage note help symbol ...
    s|&(uninfosym);|<z_$1>&#xE044;</z_$1>|g;	# usage note info symbol ...
    s|&(unmiscsym);|<z_$1>&#xE046;</z_$1>|g;	# usage note misc symbol ...	
    s|&(unmoresym);|<z_$1>&#xE043;</z_$1>|g;	# usage note more symbol ...
    s|&(unnotesym);|<z_$1>&#xE04F;</z_$1>|g;		# usage note "note" symbol ...
    s|&(unoppsym);|<z_$1>&#xE049;</z_$1>|g;		# usage note opposite symbol ...
    s|&(unspelsym);|<z_$1>&#xE04A;</z_$1>|g;	# usage note spelling symbol ...
    s|&(unstylesym);|<z_$1>&#xE04B;</z_$1>|g;	# usage note style symbol ...
    s|&(unsynsym);|<z_$1>&#xE04C;</z_$1>|g;		# usage note synonyms symbol ...
    s|&(untopicsym);|<z_$1>&#xE03F;</z_$1>|g;	# usage note topic symbol ...
    s|&(unussym);|<z_$1>&#xE04D;</z_$1>|g;		# usage note US symbol ...
    s|&(unvocsym);|<z_$1>&#xE04E;</z_$1>|g;		# usage note voc symbol ...
#   cross-reference symbols ...
    s|&(xrarrowsym);|<z_$1>&#xE08A;</z_$1>|g;	# cross-reference arrow symbol ...
    s|&(xrequalssym);|<z_$1>=</z_$1>|g;	# cross-reference equals symbol - as requested this is a normal equals character but processed here for consistency with other symbols...
    s|&(xrlookatsym);|<z_$1>&#xE08D;</z_$1>|g;	# cross-reference arrow symbol ...
    s|&(xrnoteatsym);|<z_$1>&#xE08E;</z_$1>|g;	# cross-reference arrow symbol ...
    s|&(xroppsym);|<z_$1>&#xE08C;</z_$1>|g;	# cross-reference opposite symbol ...
    s|&(xrpicatsym);|<z_$1>&#xE08F;</z_$1>|g;	# cross-reference arrow symbol ...
    s|&(xrpiconsym);|<z_$1>&#xE090;</z_$1>|g;	# cross-reference arrow symbol ...
    s|&(xrsym);|<z_$1>&#xE08A;</z_$1>|g;	# cross-reference default symbol ...
    s|&(xrsynsym);|<z_$1>&#xE08B;</z_$1>|g;	# cross-reference synonym symbol ...
#    separator symbols - used to separate multiple elements of the same type ... 	
    s|&(clgsep);|<z_$1>&#xE0D0;</z_$1>|g;	# adjacent collocate groups separator/divider (eg EAP) ...
    s|&(drsep);|<z_$1>&#xE0CD;</z_$1>|g;	# adjacent derivative groups separator...
    s|&(idsep);|<z_$1>&#xE0CE;</z_$1>|g;	# adjacent idiom groups separator...
    s|&(lisep);|<z_$1>&#xE0D2;</z_$1>|g;	# inline list item separator ...
    s|&(pvsep);|<z_$1>&#xE0CF;</z_$1>|g;	# adjacent phrasal verb groups separator...
    s|&(sbgsep);|<z_$1>&#xE0D1;</z_$1>|g;	# adjacent sense groups separator/divider (eg EAP) ...
    s|&(xsep);|<z_$1>&#xE0CA;</z_$1>|g;	# example separator symbol ...
}

1;
